const NORMAL_ACCOUNT = 'C';
const ADMIN_ACCOUNT = 'A';
const DISABLED_ACCOUNT = 'D';
const INACTIVATED_ACCOUNT = 'I';
const DEFAULT_ACCOUNT = NORMAL_ACCOUNT;

module.exports = {
  DEFAULT: DEFAULT_ACCOUNT,
  NORMAL: NORMAL_ACCOUNT,
  ADMIN: ADMIN_ACCOUNT,
  DISABLED: DISABLED_ACCOUNT,
  INACTIVATED: INACTIVATED_ACCOUNT,
};
