const ACTIVE_ACCOUNT = 'A';
const DISABLED_ACCOUNT = 'D';
const INACTIVATED_ACCOUNT = 'I';
const DEFAULT_ACCOUNT = ACTIVE_ACCOUNT;

module.exports = {
  DEFAULT: DEFAULT_ACCOUNT,
  DISABLED: DISABLED_ACCOUNT,
  ACTIVE: ACTIVE_ACCOUNT,
  INACTIVATED: INACTIVATED_ACCOUNT,
};
